/* File automatically generated by genmdesc, don't change */

const char mono_x86_desc [] = {
	"\x0\x0\x0\x0\x0\x0"	/* null entry */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* nop */
	"\x0" "\x0" "\x0" "\x0" "\x1" "\x0" ""	/* hard_nop */
	"\x0" "\x0" "\x0" "\x0" "\x2" "\x0" ""	/* relaxed_nop */
	"\x0" "ii\x0" "\x2" "\x0" ""	/* compare */
	"\x0" "i\x0" "\x0" "\x6" "\x0" ""	/* compare_imm */
	"\x0" "ff\x0" "\x9" "a"	/* fcompare */
	"\x0" "ii\x0" "\x2" "\x0" ""	/* icompare */
	"\x0" "i\x0" "\x0" "\x6" "\x0" ""	/* icompare_imm */
	"ii\x0" "\x0" "x\x0" ""	/* localloc */
	"i\x0" "\x0" "\x0" "x\x0" ""	/* localloc_imm */
	"\x0" "b\x0" "\x0" "\x3" "\x0" ""	/* checkthis */
	"\x0" "\x0" "\x0" "\x0" "\x1a" "c"	/* seq_point */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* il_seq_point */
	"\x0" "\x0" "\x0" "\x0" "\x11" "c"	/* voidcall */
	"\x0" "i\x0" "\x0" "\xb" "c"	/* voidcall_reg */
	"\x0" "b\x0" "\x0" "\x10" "c"	/* voidcall_membase */
	"a\x0" "\x0" "\x0" "\x11" "c"	/* call */
	"ai\x0" "\x0" "\xb" "c"	/* call_reg */
	"ab\x0" "\x0" "\x10" "c"	/* call_membase */
	"f\x0" "\x0" "\x0" "\x11" "c"	/* fcall */
	"fi\x0" "\x0" "\xb" "c"	/* fcall_reg */
	"fb\x0" "\x0" "\x10" "c"	/* fcall_membase */
	"l\x0" "\x0" "\x0" "\x11" "c"	/* lcall */
	"li\x0" "\x0" "\xb" "c"	/* lcall_reg */
	"lb\x0" "\x0" "\x10" "c"	/* lcall_membase */
	"\x0" "\x0" "\x0" "\x0" "\x11" "c"	/* vcall */
	"\x0" "i\x0" "\x0" "\xb" "c"	/* vcall_reg */
	"\x0" "b\x0" "\x0" "\x10" "c"	/* vcall_membase */
	"\x0" "\x0" "\x0" "\x0" "\x11" "c"	/* vcall2 */
	"\x0" "i\x0" "\x0" "\xb" "c"	/* vcall2_reg */
	"\x0" "b\x0" "\x0" "\x10" "c"	/* vcall2_membase */
	"i\x0" "\x0" "\x0" "\x5" "\x0" ""	/* iconst */
	"f\x0" "\x0" "\x0" "\xf" "\x0" ""	/* r4const */
	"f\x0" "\x0" "\x0" "\x10" "\x0" ""	/* r8const */
	"i\x0" "\x0" "\x0" "\x0" "\x0" ""	/* dummy_iconst */
	"f\x0" "\x0" "\x0" "\x0" "\x0" ""	/* dummy_r8const */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* label */
	"\x0" "i\x0" "\x0" "\xd" "\x0" ""	/* throw */
	"\x0" "i\x0" "\x0" "\xd" "\x0" ""	/* rethrow */
	"\x0" "b\x0" "\x0" "\xa" "\x0" ""	/* oparglist */
	"bi\x0" "\x0" "\x7" "\x0" ""	/* store_membase_reg */
	"by\x0" "\x0" "\x7" "\x0" ""	/* storei1_membase_reg */
	"bi\x0" "\x0" "\x7" "\x0" ""	/* storei2_membase_reg */
	"bi\x0" "\x0" "\x7" "\x0" ""	/* storei4_membase_reg */
	"bi\x0" "\x0" "\x0" "\x0" ""	/* storei8_membase_reg */
	"bf\x0" "\x0" "\x7" "\x0" ""	/* storer4_membase_reg */
	"bf\x0" "\x0" "\x7" "\x0" ""	/* storer8_membase_reg */
	"bx\x0" "\x0" "\x7" "\x0" ""	/* storex_membase_reg */
	"bx\x0" "\x0" "\x7" "\x0" ""	/* storex_aligned_membase_reg */
	"bx\x0" "\x0" "\x7" "\x0" ""	/* storex_nta_membase_reg */
	"b\x0" "\x0" "\x0" "\xb" "\x0" ""	/* store_membase_imm */
	"b\x0" "\x0" "\x0" "\xa" "\x0" ""	/* storei1_membase_imm */
	"b\x0" "\x0" "\x0" "\xb" "\x0" ""	/* storei2_membase_imm */
	"b\x0" "\x0" "\x0" "\xa" "\x0" ""	/* storei4_membase_imm */
	"b\x0" "\x0" "\x0" "\x0" "\x0" ""	/* storei8_membase_imm */
	"bx\x0" "\x0" "\x7" "\x0" ""	/* storex_membase */
	"ib\x0" "\x0" "\x7" "\x0" ""	/* load_membase */
	"yb\x0" "\x0" "\x7" "\x0" ""	/* loadi1_membase */
	"yb\x0" "\x0" "\x7" "\x0" ""	/* loadu1_membase */
	"ib\x0" "\x0" "\x7" "\x0" ""	/* loadi2_membase */
	"ib\x0" "\x0" "\x7" "\x0" ""	/* loadu2_membase */
	"ib\x0" "\x0" "\x7" "\x0" ""	/* loadi4_membase */
	"ib\x0" "\x0" "\x7" "\x0" ""	/* loadu4_membase */
	"ib\x0" "\x0" "\x0" "\x0" ""	/* loadi8_membase */
	"fb\x0" "\x0" "\x7" "\x0" ""	/* loadr4_membase */
	"fb\x0" "\x0" "\x7" "\x0" ""	/* loadr8_membase */
	"xb\x0" "\x0" "\x7" "\x0" ""	/* loadx_membase */
	"xb\x0" "\x0" "\x7" "\x0" ""	/* loadx_aligned_membase */
	"i\x0" "\x0" "\x0" "\x9" "\x0" ""	/* load_mem */
	"i\x0" "\x0" "\x0" "\x9" "\x0" ""	/* loadu1_mem */
	"i\x0" "\x0" "\x0" "\x9" "\x0" ""	/* loadu2_mem */
	"i\x0" "\x0" "\x0" "\x9" "\x0" ""	/* loadi4_mem */
	"i\x0" "\x0" "\x0" "\x9" "\x0" ""	/* loadu4_mem */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\x0" ""	/* store_mem_imm */
	"ii\x0" "\x0" "\x2" "\x0" ""	/* move */
	"ff\x0" "\x0" "\x0" "\x0" ""	/* fmove */
	"if\x0" "\x0" "\x11" "\x0" ""	/* move_f_to_i4 */
	"fi\x0" "\x0" "\x11" "\x0" ""	/* move_i4_to_f */
	"ii\x0" "\x0" "\x6" "1"	/* add_imm */
	"ii\x0" "\x0" "\x6" "1"	/* sub_imm */
	"ii\x0" "\x0" "\x9" "\x0" ""	/* mul_imm */
	"ii\x0" "\x0" "\x6" "1"	/* and_imm */
	"ii\x0" "\x0" "\x6" "1"	/* or_imm */
	"ii\x0" "\x0" "\x6" "1"	/* xor_imm */
	"ii\x0" "\x0" "\x6" "1"	/* shl_imm */
	"ii\x0" "\x0" "\x6" "1"	/* shr_imm */
	"ii\x0" "\x0" "\x6" "1"	/* shr_un_imm */
	"\x0" "\x0" "\x0" "\x0" "\x5" "\x0" ""	/* br */
	"\x0" "\x0" "\x0" "\x0" "xc"	/* tailcall */
	"\x0" "\x0" "\x0" "\x0" "\x1" "\x0" ""	/* break */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* ceq */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cgt */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cgt.un */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* clt */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* clt.un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_eq */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ge */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_gt */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_le */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_lt */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ne_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ge_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_gt_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_le_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_lt_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ov */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_no */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_c */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_nc */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ieq */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ige */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_igt */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ile */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ilt */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ine_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ige_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_igt_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ile_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ilt_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_iov */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ino */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_ic */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* cond_exc_inc */
	"LLs\x0" "\x15" "1"	/* long_shl */
	"LLs\x0" "\x16" "1"	/* long_shr */
	"LLs\x0" "\x16" "1"	/* long_shr_un */
	"LL\x0" "\x0" "\xa" "1"	/* long_shl_imm */
	"LL\x0" "\x0" "\xa" "1"	/* long_shr_imm */
	"LL\x0" "\x0" "\xa" "1"	/* long_shr_un_imm */
	"fii\x0" "\xe" "\x0" ""	/* long_conv_to_r8_2 */
	"fii\x0" "\xe" "\x0" ""	/* long_conv_to_r4_2 */
	"fii\x0" "\x28" "\x0" ""	/* long_conv_to_r_un_2 */
	"iii\x0" "\x1e" "\x0" ""	/* long_conv_to_ovf_i4_2 */
	"iii\x0" "\x2" "1"	/* int_add */
	"iii\x0" "\x2" "1"	/* int_sub */
	"iii\x0" "\x3" "1"	/* int_mul */
	"aai\x0" "\xf" "d"	/* int_div */
	"aai\x0" "\xf" "d"	/* int_div_un */
	"dai\x0" "\xf" "a"	/* int_rem */
	"dai\x0" "\xf" "a"	/* int_rem_un */
	"iii\x0" "\x2" "1"	/* int_and */
	"iii\x0" "\x2" "1"	/* int_or */
	"iii\x0" "\x2" "1"	/* int_xor */
	"iis\x0" "\x2" "1"	/* int_shl */
	"iis\x0" "\x2" "1"	/* int_shr */
	"iis\x0" "\x2" "1"	/* int_shr_un */
	"ii\x0" "\x0" "\x2" "1"	/* int_neg */
	"ii\x0" "\x0" "\x2" "1"	/* int_not */
	"iy\x0" "\x0" "\x3" "\x0" ""	/* int_conv_to_i1 */
	"ii\x0" "\x0" "\x3" "\x0" ""	/* int_conv_to_i2 */
	"ii\x0" "\x0" "\x2" "\x0" ""	/* int_conv_to_i4 */
	"fi\x0" "\x0" "\xd" "\x0" ""	/* int_conv_to_r4 */
	"fi\x0" "\x0" "\x7" "\x0" ""	/* int_conv_to_r8 */
	"ii\x0" "\x0" "\x0" "\x0" ""	/* int_conv_to_u4 */
	"fi\x0" "\x0" "\x20" "\x0" ""	/* int_conv_to_r_un */
	"ii\x0" "\x0" "\x3" "\x0" ""	/* int_conv_to_u2 */
	"iy\x0" "\x0" "\x3" "\x0" ""	/* int_conv_to_u1 */
	"ii\x0" "\x0" "\x3" "\x0" ""	/* int_conv_to_i */
	"iii\x0" "\x9" "1"	/* int_mul_ovf */
	"iii\x0" "\x10" "\x0" ""	/* int_mul_ovf_un */
	"iii\x0" "\x2" "1"	/* int_adc */
	"iii\x0" "\x2" "1"	/* int_sbb */
	"iii\x0" "\x2" "1"	/* int_addcc */
	"iii\x0" "\x2" "1"	/* int_subcc */
	"ii\x0" "\x0" "\x6" "1"	/* int_add_imm */
	"ii\x0" "\x0" "\x6" "1"	/* int_sub_imm */
	"ii\x0" "\x0" "\x9" "\x0" ""	/* int_mul_imm */
	"aa\x0" "\x0" "\xf" "d"	/* int_div_imm */
	"aa\x0" "\x0" "\xf" "d"	/* int_div_un_imm */
	"aa\x0" "\x0" "\xf" "d"	/* int_rem_imm */
	"da\x0" "\x0" "\xf" "a"	/* int_rem_un_imm */
	"ii\x0" "\x0" "\x6" "1"	/* int_and_imm */
	"ii\x0" "\x0" "\x6" "1"	/* int_or_imm */
	"ii\x0" "\x0" "\x6" "1"	/* int_xor_imm */
	"ii\x0" "\x0" "\x6" "1"	/* int_shl_imm */
	"ii\x0" "\x0" "\x6" "1"	/* int_shr_imm */
	"ii\x0" "\x0" "\x6" "1"	/* int_shr_un_imm */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_ceq */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_cgt */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_cgt_un */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_clt */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_clt_un */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_cneq */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_cge */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_cle */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_cge_un */
	"y\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_cle_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_beq */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_bge */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_bgt */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_ble */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_blt */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_bne_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_bge_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_bgt_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_ble_un */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* int_blt_un */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\x0" ""	/* float_beq */
	"\x0" "\x0" "\x0" "\x0" "\x16" "\x0" ""	/* float_bge */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\x0" ""	/* float_bgt */
	"\x0" "\x0" "\x0" "\x0" "\x16" "\x0" ""	/* float_ble */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\x0" ""	/* float_blt */
	"\x0" "\x0" "\x0" "\x0" "\x12" "\x0" ""	/* float_bne_un */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\x0" ""	/* float_bge_un */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x0" ""	/* float_bgt_un */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\x0" ""	/* float_ble_un */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x0" ""	/* float_blt_un */
	"fff\x0" "\x2" "\x0" ""	/* float_add */
	"fff\x0" "\x2" "\x0" ""	/* float_sub */
	"fff\x0" "\x2" "\x0" ""	/* float_mul */
	"fff\x0" "\x2" "\x0" ""	/* float_div */
	"fff\x0" "\x2" "\x0" ""	/* float_div_un */
	"fff\x0" "\x11" "\x0" ""	/* float_rem */
	"fff\x0" "\x11" "\x0" ""	/* float_rem_un */
	"ff\x0" "\x0" "\x2" "\x0" ""	/* float_neg */
	"ff\x0" "\x0" "\x2" "\x0" ""	/* float_not */
	"yf\x0" "\x0" "\x27" "\x0" ""	/* float_conv_to_i1 */
	"yf\x0" "\x0" "\x27" "\x0" ""	/* float_conv_to_i2 */
	"if\x0" "\x0" "\x27" "\x0" ""	/* float_conv_to_i4 */
	"Lf\x0" "\x0" "\x27" "\x0" ""	/* float_conv_to_i8 */
	"ff\x0" "\x0" "\xc" "\x0" ""	/* float_conv_to_r4 */
	"if\x0" "\x0" "\x27" "\x0" ""	/* float_conv_to_u4 */
	"Lf\x0" "\x0" "\x27" "\x0" ""	/* float_conv_to_u8 */
	"yf\x0" "\x0" "\x27" "\x0" ""	/* float_conv_to_u2 */
	"yf\x0" "\x0" "\x27" "\x0" ""	/* float_conv_to_u1 */
	"if\x0" "\x0" "\x27" "\x0" ""	/* float_conv_to_i */
	"af\x0" "\x0" "\x1e" "\x0" ""	/* float_conv_to_ovf_i */
	"af\x0" "\x0" "\x1e" "\x0" ""	/* float_conv_to_ovd_u */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* float_mul_ovf */
	"yff\x0" "\x19" "\x0" ""	/* float_ceq */
	"yff\x0" "\x19" "\x0" ""	/* float_cgt */
	"yff\x0" "\x25" "\x0" ""	/* float_cgt_un */
	"yff\x0" "\x19" "\x0" ""	/* float_clt */
	"yff\x0" "\x20" "\x0" ""	/* float_clt_un */
	"yff\x0" "\x19" "\x0" ""	/* float_cneq */
	"yff\x0" "\x25" "\x0" ""	/* float_cge */
	"yff\x0" "\x25" "\x0" ""	/* float_cle */
	"if\x0" "\x0" "\x24" "\x0" ""	/* float_conv_to_u */
	"ff\x0" "\x0" "\x20" "\x0" ""	/* ckfinite */
	"i\x0" "\x0" "\x0" "\x5" "\x0" ""	/* jump_table */
	"i\x0" "\x0" "\x0" "\x5" "\x0" ""	/* aot_const */
	"ib\x0" "\x0" "\x7" "\x0" ""	/* got_entry */
	"\x0" "\x0" "\x0" "\x0" "\xb" "c"	/* call_handler */
	"\x0" "\x0" "\x0" "\x0" "\x10" "\x0" ""	/* start_handler */
	"\x0" "a\x0" "\x0" "\x10" "\x0" ""	/* endfilter */
	"\x0" "\x0" "\x0" "\x0" "\x10" "\x0" ""	/* endfinally */
	"a\x0" "\x0" "\x0" "\x10" "\x0" ""	/* get_ex_obj */
	"lai\x0" "\x2" "\x0" ""	/* bigmul */
	"lai\x0" "\x2" "\x0" ""	/* bigmul_un */
	"iii\x0" "\x10" "1"	/* int_min_un */
	"iii\x0" "\x10" "1"	/* int_max_un */
	"iii\x0" "\x10" "1"	/* int_min */
	"iii\x0" "\x10" "1"	/* int_max */
	"iii\x0" "\x2" "1"	/* adc */
	"ii\x0" "\x0" "\x6" "1"	/* adc_imm */
	"iii\x0" "\x2" "1"	/* sbb */
	"ii\x0" "\x0" "\x6" "1"	/* sbb_imm */
	"iii\x0" "\x2" "1"	/* addcc */
	"ii\x0" "\x0" "\x6" "1"	/* addcc_imm */
	"iii\x0" "\x2" "1"	/* subcc */
	"ii\x0" "\x0" "\x6" "1"	/* subcc_imm */
	"\x0" "i\x0" "\x0" "\x2" "\x0" ""	/* br_reg */
	"iy\x0" "\x0" "\x3" "\x0" ""	/* sext_i1 */
	"iy\x0" "\x0" "\x3" "\x0" ""	/* sext_i2 */
	"ff\x0" "\x0" "\x6" "\x0" ""	/* sin */
	"ff\x0" "\x0" "\x6" "\x0" ""	/* cos */
	"ff\x0" "\x0" "\x2" "\x0" ""	/* abs */
	"ff\x0" "\x0" "1\x0" ""	/* tan */
	"ff\x0" "\x0" "\x8" "\x0" ""	/* atan */
	"ff\x0" "\x0" "\x2" "\x0" ""	/* sqrt */
	"ff\x0" "\x0" "\x2" "\x0" ""	/* round */
	"\x0" "ai\x0" "\x22" "d"	/* card_table_wbarrier */
	"i\x0" "\x0" "\x0" "\x20" "\x0" ""	/* tls_get */
	"\x0" "i\x0" "\x0" "\x14" "\x0" ""	/* tls_set */
	"i\x0" "\x0" "\x0" "\x40" "\x0" ""	/* load_gotaddr */
	"\x0" "i\x0" "\x0" "\x0" "\x0" ""	/* dummy_use */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* dummy_store */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* not_reached */
	"\x0" "i\x0" "\x0" "\x0" "\x0" ""	/* not_null */
	"xxx\x0" "\x3" "1"	/* addps */
	"xxx\x0" "\x3" "1"	/* divps */
	"xxx\x0" "\x3" "1"	/* mulps */
	"xxx\x0" "\x3" "1"	/* subps */
	"xxx\x0" "\x3" "1"	/* maxps */
	"xxx\x0" "\x3" "1"	/* minps */
	"xxx\x0" "\x4" "1"	/* compps */
	"xxx\x0" "\x3" "1"	/* andps */
	"xxx\x0" "\x3" "1"	/* andnps */
	"xxx\x0" "\x3" "1"	/* orps */
	"xxx\x0" "\x3" "1"	/* xorps */
	"xxx\x0" "\x4" "1"	/* haddps */
	"xxx\x0" "\x4" "1"	/* hsubps */
	"xxx\x0" "\x4" "1"	/* addsubps */
	"xx\x0" "\x0" "\x4" "\x0" ""	/* dupps_low */
	"xx\x0" "\x0" "\x4" "\x0" ""	/* dupps_high */
	"xx\x0" "\x0" "\x4" "\x0" ""	/* rsqrtps */
	"xx\x0" "\x0" "\x4" "\x0" ""	/* sqrtps */
	"xx\x0" "\x0" "\x4" "\x0" ""	/* rcpps */
	"xx\x0" "\x0" "\x5" "\x0" ""	/* pshufflew_high */
	"xx\x0" "\x0" "\x5" "\x0" ""	/* pshufflew_low */
	"xx\x0" "\x0" "\x5" "\x0" ""	/* pshuffled */
	"xxx\x0" "\x4" "1"	/* shufps */
	"xxx\x0" "\x5" "1"	/* shufpd */
	"xxx\x0" "\x4" "1"	/* addpd */
	"xxx\x0" "\x4" "1"	/* divpd */
	"xxx\x0" "\x4" "1"	/* mulpd */
	"xxx\x0" "\x4" "1"	/* subpd */
	"xxx\x0" "\x4" "1"	/* maxpd */
	"xxx\x0" "\x4" "1"	/* minpd */
	"xxx\x0" "\x5" "1"	/* comppd */
	"xxx\x0" "\x4" "1"	/* andpd */
	"xxx\x0" "\x4" "1"	/* andnpd */
	"xxx\x0" "\x4" "1"	/* orpd */
	"xxx\x0" "\x4" "1"	/* xorpd */
	"xxx\x0" "\x5" "1"	/* haddpd */
	"xxx\x0" "\x5" "1"	/* hsubpd */
	"xxx\x0" "\x5" "1"	/* addsubpd */
	"xx\x0" "\x0" "\x5" "\x0" ""	/* duppd */
	"xx\x0" "\x0" "\x4" "1"	/* sqrtpd */
	"ix\x0" "\x0" "\x4" "\x0" ""	/* extract_mask */
	"xxx\x0" "\x4" "1"	/* pand */
	"xxx\x0" "\x4" "1"	/* por */
	"xxx\x0" "\x4" "1"	/* pxor */
	"xxx\x0" "\x4" "1"	/* paddb */
	"xxx\x0" "\x4" "1"	/* paddw */
	"xxx\x0" "\x4" "1"	/* paddd */
	"xxx\x0" "\x4" "1"	/* paddq */
	"xxx\x0" "\x4" "1"	/* psubb */
	"xxx\x0" "\x4" "1"	/* psubw */
	"xxx\x0" "\x4" "1"	/* psubd */
	"xxx\x0" "\x4" "1"	/* psubq */
	"xxx\x0" "\x4" "1"	/* pmaxb_un */
	"xxx\x0" "\x5" "1"	/* pmaxw_un */
	"xxx\x0" "\x5" "1"	/* pmaxd_un */
	"xxx\x0" "\x5" "1"	/* pmaxb */
	"xxx\x0" "\x4" "1"	/* pmaxw */
	"xxx\x0" "\x5" "1"	/* pmaxd */
	"xxx\x0" "\x4" "1"	/* pavgb_un */
	"xxx\x0" "\x4" "1"	/* pavgw_un */
	"xxx\x0" "\x4" "1"	/* pminb_un */
	"xxx\x0" "\x5" "1"	/* pminw_un */
	"xxx\x0" "\x5" "1"	/* pmind_un */
	"xxx\x0" "\x5" "1"	/* pminb */
	"xxx\x0" "\x4" "1"	/* pminw */
	"xxx\x0" "\x5" "1"	/* pmind */
	"xxx\x0" "\x4" "1"	/* pcmpeqb */
	"xxx\x0" "\x4" "1"	/* pcmpeqw */
	"xxx\x0" "\x4" "1"	/* pcmpeqd */
	"xxx\x0" "\x5" "1"	/* pcmpeqq */
	"xxx\x0" "\x4" "1"	/* pcmpgtb */
	"xxx\x0" "\x4" "1"	/* pcmpgtw */
	"xxx\x0" "\x4" "1"	/* pcmpgtd */
	"xxx\x0" "\x5" "1"	/* pcmpgtq */
	"xxx\x0" "\x4" "1"	/* psumabsdiff */
	"xxx\x0" "\x4" "1"	/* unpack_lowb */
	"xxx\x0" "\x4" "1"	/* unpack_loww */
	"xxx\x0" "\x4" "1"	/* unpack_lowd */
	"xxx\x0" "\x4" "1"	/* unpack_lowq */
	"xxx\x0" "\x3" "1"	/* unpack_lowps */
	"xxx\x0" "\x4" "1"	/* unpack_lowpd */
	"xxx\x0" "\x4" "1"	/* unpack_highb */
	"xxx\x0" "\x4" "1"	/* unpack_highw */
	"xxx\x0" "\x4" "1"	/* unpack_highd */
	"xxx\x0" "\x4" "1"	/* unpack_highq */
	"xxx\x0" "\x3" "1"	/* unpack_highps */
	"xxx\x0" "\x4" "1"	/* unpack_highpd */
	"xxx\x0" "\x4" "1"	/* packw */
	"xxx\x0" "\x4" "1"	/* packd */
	"xxx\x0" "\x4" "1"	/* packw_un */
	"xxx\x0" "\x5" "1"	/* packd_un */
	"xxx\x0" "\x4" "1"	/* paddb_sat */
	"xxx\x0" "\x4" "1"	/* paddb_sat_un */
	"xxx\x0" "\x4" "1"	/* paddw_sat */
	"xxx\x0" "\x4" "1"	/* paddw_sat_un */
	"xxx\x0" "\x4" "1"	/* psubb_sat */
	"xxx\x0" "\x4" "1"	/* psubb_sat_un */
	"xxx\x0" "\x4" "1"	/* psubw_sat */
	"xxx\x0" "\x4" "1"	/* psubw_sat_un */
	"xxx\x0" "\x4" "1"	/* pmulw */
	"xxx\x0" "\x5" "1"	/* pmuld */
	"xxx\x0" "\x4" "1"	/* pmulq */
	"xxx\x0" "\x4" "1"	/* pmul_high_un */
	"xxx\x0" "\x4" "1"	/* pmul_high */
	"xx\x0" "\x0" "\x5" "1"	/* pshrw */
	"xxx\x0" "\x4" "1"	/* pshrw_reg */
	"xx\x0" "\x0" "\x5" "1"	/* psarw */
	"xxx\x0" "\x4" "1"	/* psarw_reg */
	"xx\x0" "\x0" "\x5" "1"	/* pshlw */
	"xxx\x0" "\x4" "1"	/* pshlw_reg */
	"xx\x0" "\x0" "\x5" "1"	/* pshrd */
	"xxx\x0" "\x4" "1"	/* pshrd_reg */
	"xx\x0" "\x0" "\x5" "1"	/* pshrq */
	"xxx\x0" "\x4" "1"	/* pshrq_reg */
	"xx\x0" "\x0" "\x5" "1"	/* psard */
	"xxx\x0" "\x4" "1"	/* psard_reg */
	"xx\x0" "\x0" "\x5" "1"	/* pshld */
	"xxx\x0" "\x4" "1"	/* pshld_reg */
	"xx\x0" "\x0" "\x5" "1"	/* pshlq */
	"xxx\x0" "\x4" "1"	/* pshlq_reg */
	"ix\x0" "\x0" "\x4" "\x0" ""	/* extract_i4 */
	"ix\x0" "\x0" "\xa" "\x0" ""	/* extract_i2 */
	"ix\x0" "\x0" "\xa" "\x0" ""	/* extract_u2 */
	"ix\x0" "\x0" "\xa" "\x0" ""	/* extract_i1 */
	"ix\x0" "\x0" "\xa" "\x0" ""	/* extract_u1 */
	"fx\x0" "\x0" "\x8" "\x0" ""	/* extract_r8 */
	"xxi\x0" "\x5" "1"	/* insert_i2 */
	"ix\x0" "\x0" "\x5" "\x0" ""	/* extractx_u2 */
	"xii\x0" "\x10" "x"	/* insertx_u1_slow */
	"xxi\x0" "\xd" "x"	/* insertx_i4_slow */
	"xxf\x0" "\x18" "1"	/* insertx_r4_slow */
	"xxf\x0" "\x18" "1"	/* insertx_r8_slow */
	"xf\x0" "\x0" "\xe" "\x0" ""	/* fconv_to_r8_x */
	"yx\x0" "\x0" "\x7" "\x0" ""	/* xconv_r8_to_i4 */
	"xi\x0" "\x0" "\x4" "\x0" ""	/* iconv_to_x */
	"xi\x0" "\x0" "\xf" "\x0" ""	/* expand_i2 */
	"xi\x0" "\x0" "\x9" "\x0" ""	/* expand_i4 */
	"xf\x0" "\x0" "\x14" "\x0" ""	/* expand_r4 */
	"xf\x0" "\x0" "\x14" "\x0" ""	/* expand_r8 */
	"\x0" "b\x0" "\x0" "\x4" "\x0" ""	/* prefetch_membase */
	"xx\x0" "\x0" "\x4" "1"	/* cvtdq2pd */
	"xx\x0" "\x0" "\x3" "1"	/* cvtdq2ps */
	"xx\x0" "\x0" "\x4" "1"	/* cvtpd2dq */
	"xx\x0" "\x0" "\x4" "1"	/* cvtpd2ps */
	"xx\x0" "\x0" "\x4" "1"	/* cvtps2dq */
	"xx\x0" "\x0" "\x3" "1"	/* cvtps2pd */
	"xx\x0" "\x0" "\x4" "1"	/* cvttpd2dq */
	"xx\x0" "\x0" "\x4" "1"	/* cvttps2dq */
	"xx\x0" "\x0" "\x4" "\x0" ""	/* xmove */
	"x\x0" "\x0" "\x0" "\x4" "\x0" ""	/* xzero */
	"x\x0" "\x0" "\x0" "\x4" "\x0" ""	/* xones */
	"\x0" "\x0" "\x0" "\x0" "\x10" "\x0" ""	/* memory_barrier */
	"yb\x0" "\x0" "\x7" "\x0" ""	/* atomic_load_i1 */
	"ib\x0" "\x0" "\x7" "\x0" ""	/* atomic_load_i2 */
	"ib\x0" "\x0" "\x7" "\x0" ""	/* atomic_load_i4 */
	"yb\x0" "\x0" "\x7" "\x0" ""	/* atomic_load_u1 */
	"ib\x0" "\x0" "\x7" "\x0" ""	/* atomic_load_u2 */
	"ib\x0" "\x0" "\x7" "\x0" ""	/* atomic_load_u4 */
	"fb\x0" "\x0" "\xa" "\x0" ""	/* atomic_load_r4 */
	"fb\x0" "\x0" "\xa" "\x0" ""	/* atomic_load_r8 */
	"by\x0" "\x0" "\xa" "\x0" ""	/* atomic_store_i1 */
	"bi\x0" "\x0" "\xa" "\x0" ""	/* atomic_store_i2 */
	"bi\x0" "\x0" "\xa" "\x0" ""	/* atomic_store_i4 */
	"by\x0" "\x0" "\xa" "\x0" ""	/* atomic_store_u1 */
	"bi\x0" "\x0" "\xa" "\x0" ""	/* atomic_store_u2 */
	"bi\x0" "\x0" "\xa" "\x0" ""	/* atomic_store_u4 */
	"bf\x0" "\x0" "\xa" "\x0" ""	/* atomic_store_r4 */
	"bf\x0" "\x0" "\xa" "\x0" ""	/* atomic_store_r8 */
	"ibi\x0" "\x10" "\x0" ""	/* atomic_add_i4 */
	"abi\x0" "\x18" "\x0" ""	/* atomic_exchange_i4 */
	"abia\x18" "\x0" ""	/* atomic_cas_i4 */
	"iii\x0" "\x10" "1"	/* cmov_ieq */
	"iii\x0" "\x10" "1"	/* cmov_ige */
	"iii\x0" "\x10" "1"	/* cmov_igt */
	"iii\x0" "\x10" "1"	/* cmov_ile */
	"iii\x0" "\x10" "1"	/* cmov_ilt */
	"iii\x0" "\x10" "1"	/* cmov_ine_un */
	"iii\x0" "\x10" "1"	/* cmov_ige_un */
	"iii\x0" "\x10" "1"	/* cmov_igt_un */
	"iii\x0" "\x10" "1"	/* cmov_ile_un */
	"iii\x0" "\x10" "1"	/* cmov_ilt_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* liverange_start */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* liverange_end */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* gc_liveness_def */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* gc_liveness_use */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* gc_spill_slot_liveness_def */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* gc_param_slot_liveness_def */
	"\x0" "i\x0" "\x0" "\x14" "c"	/* gc_safe_point */
	"\x0" "i\x0" "\x0" "\x2" "\x0" ""	/* x86_test_null */
	"\x0" "bi\x0" "\x7" "\x0" ""	/* x86_compare_membase_reg */
	"\x0" "b\x0" "\x0" "\xb" "\x0" ""	/* x86_compare_membase_imm */
	"\x0" "\x0" "\x0" "\x0" "\xb" "\x0" ""	/* x86_compare_mem_imm */
	"\x0" "b\x0" "\x0" "\x8" "\x0" ""	/* x86_compare_membase8_imm */
	"\x0" "ib\x0" "\x7" "\x0" ""	/* x86_compare_reg_membase */
	"ii\x0" "\x0" "\x1" "1"	/* x86_inc_reg */
	"\x0" "b\x0" "\x0" "\x7" "\x0" ""	/* x86_inc_membase */
	"ii\x0" "\x0" "\x1" "1"	/* x86_dec_reg */
	"\x0" "b\x0" "\x0" "\x7" "\x0" ""	/* x86_dec_membase */
	"\x0" "b\x0" "\x0" "\xb" "\x0" ""	/* x86_add_membase_imm */
	"\x0" "b\x0" "\x0" "\xb" "\x0" ""	/* x86_sub_membase_imm */
	"\x0" "b\x0" "\x0" "\xb" "\x0" ""	/* x86_and_membase_imm */
	"\x0" "b\x0" "\x0" "\xb" "\x0" ""	/* x86_or_membase_imm */
	"\x0" "b\x0" "\x0" "\xb" "\x0" ""	/* x86_xor_membase_imm */
	"\x0" "bi\x0" "\xb" "\x0" ""	/* x86_add_membase_reg */
	"\x0" "bi\x0" "\xb" "\x0" ""	/* x86_sub_membase_reg */
	"\x0" "bi\x0" "\xb" "\x0" ""	/* x86_and_membase_reg */
	"\x0" "bi\x0" "\xb" "\x0" ""	/* x86_or_membase_reg */
	"\x0" "bi\x0" "\xb" "\x0" ""	/* x86_xor_membase_reg */
	"\x0" "bi\x0" "\xd" "\x0" ""	/* x86_mul_membase_reg */
	"iib\x0" "\xb" "1"	/* x86_add_reg_membase */
	"iib\x0" "\xb" "1"	/* x86_sub_reg_membase */
	"iib\x0" "\xd" "1"	/* x86_mul_reg_membase */
	"iib\x0" "\x6" "1"	/* x86_and_reg_membase */
	"iib\x0" "\x6" "1"	/* x86_or_reg_membase */
	"iib\x0" "\x6" "1"	/* x86_xor_reg_membase */
	"\x0" "b\x0" "\x0" "\x7" "\x0" ""	/* x86_push_membase */
	"\x0" "\x0" "\x0" "\x0" "\x5" "\x0" ""	/* x86_push_imm */
	"\x0" "i\x0" "\x0" "\x1" "\x0" ""	/* x86_push */
	"\x0" "b\x0" "\x0" "\x1e" "\x0" ""	/* x86_push_obj */
	"\x0" "b\x0" "\x0" "\x7" "\x0" ""	/* x86_push_got_entry */
	"iii\x0" "\x7" "\x0" ""	/* x86_lea */
	"ii\x0" "\x0" "\xa" "\x0" ""	/* x86_lea_membase */
	"\x0" "ii\x0" "\x1" "x"	/* x86_xchg */
	"\x0" "f\x0" "\x0" "\x2" "\x0" ""	/* x86_fpop */
	"fb\x0" "\x0" "\x7" "\x0" ""	/* x86_fp_load_i8 */
	"fb\x0" "\x0" "\x7" "\x0" ""	/* x86_fp_load_i4 */
	"\x0" "b\x0" "\x0" "\x7" "\x0" ""	/* x86_seteq_membase */
	"\x0" "b\x0" "\x0" "\x7" "\x0" ""	/* x86_setne_membase */
	"\x0" "\x0" "\x0" "\x0" "\x2" "\x0" ""	/* x86_fxch */
	"i\x0" "\x0" "\x0" "\x6" "\x0" ""	/* get_sp */
	"\x0" "i\x0" "\x0" "\x6" "\x0" ""	/* set_sp */
};

const guint16 mono_x86_desc_idx [] = {
	0,	/* load */
	0,	/* ldaddr */
	0,	/* store */
	6,	/* nop */
	12,	/* hard_nop */
	18,	/* relaxed_nop */
	0,	/* phi */
	0,	/* fphi */
	0,	/* vphi */
	24,	/* compare */
	30,	/* compare_imm */
	36,	/* fcompare */
	0,	/* rcompare */
	0,	/* lcompare */
	42,	/* icompare */
	48,	/* icompare_imm */
	0,	/* lcompare_imm */
	0,	/* local */
	0,	/* arg */
	0,	/* gsharedvt_local */
	0,	/* gsharedvt_arg_regoffset */
	0,	/* outarg_vt */
	0,	/* outarg_vtretaddr */
	0,	/* setret */
	0,	/* setfret */
	0,	/* setlret */
	54,	/* localloc */
	60,	/* localloc_imm */
	66,	/* checkthis */
	72,	/* seq_point */
	78,	/* il_seq_point */
	0,	/* implicit_exception */
	84,	/* voidcall */
	90,	/* voidcall_reg */
	96,	/* voidcall_membase */
	102,	/* call */
	108,	/* call_reg */
	114,	/* call_membase */
	120,	/* fcall */
	126,	/* fcall_reg */
	132,	/* fcall_membase */
	0,	/* rcall */
	0,	/* rcall_reg */
	0,	/* rcall_membase */
	138,	/* lcall */
	144,	/* lcall_reg */
	150,	/* lcall_membase */
	156,	/* vcall */
	162,	/* vcall_reg */
	168,	/* vcall_membase */
	174,	/* vcall2 */
	180,	/* vcall2_reg */
	186,	/* vcall2_membase */
	0,	/* dyn_call */
	192,	/* iconst */
	0,	/* i8const */
	198,	/* r4const */
	204,	/* r8const */
	210,	/* dummy_iconst */
	0,	/* dummy_i8const */
	216,	/* dummy_r8const */
	0,	/* dummy_r4const */
	0,	/* dummy_vzero */
	0,	/* regvar */
	0,	/* regoffset */
	0,	/* vtarg_addr */
	222,	/* label */
	0,	/* switch */
	228,	/* throw */
	234,	/* rethrow */
	240,	/* oparglist */
	246,	/* store_membase_reg */
	252,	/* storei1_membase_reg */
	258,	/* storei2_membase_reg */
	264,	/* storei4_membase_reg */
	270,	/* storei8_membase_reg */
	276,	/* storer4_membase_reg */
	282,	/* storer8_membase_reg */
	288,	/* storex_membase_reg */
	294,	/* storex_aligned_membase_reg */
	300,	/* storex_nta_membase_reg */
	306,	/* store_membase_imm */
	312,	/* storei1_membase_imm */
	318,	/* storei2_membase_imm */
	324,	/* storei4_membase_imm */
	330,	/* storei8_membase_imm */
	336,	/* storex_membase */
	0,	/* storev_membase */
	342,	/* load_membase */
	348,	/* loadi1_membase */
	354,	/* loadu1_membase */
	360,	/* loadi2_membase */
	366,	/* loadu2_membase */
	372,	/* loadi4_membase */
	378,	/* loadu4_membase */
	384,	/* loadi8_membase */
	390,	/* loadr4_membase */
	396,	/* loadr8_membase */
	402,	/* loadx_membase */
	408,	/* loadx_aligned_membase */
	0,	/* loadv_membase */
	0,	/* load_memindex */
	0,	/* loadi1_memindex */
	0,	/* loadu1_memindex */
	0,	/* loadi2_memindex */
	0,	/* loadu2_memindex */
	0,	/* loadi4_memindex */
	0,	/* loadu4_memindex */
	0,	/* loadi8_memindex */
	0,	/* loadr4_memindex */
	0,	/* loadr8_memindex */
	0,	/* store_memindex */
	0,	/* storei1_memindex */
	0,	/* storei2_memindex */
	0,	/* storei4_memindex */
	0,	/* storei8_memindex */
	0,	/* storer4_memindex */
	0,	/* storer8_memindex */
	414,	/* load_mem */
	420,	/* loadu1_mem */
	426,	/* loadu2_mem */
	432,	/* loadi4_mem */
	438,	/* loadu4_mem */
	0,	/* loadi8_mem */
	444,	/* store_mem_imm */
	450,	/* move */
	0,	/* lmove */
	456,	/* fmove */
	0,	/* vmove */
	0,	/* rmove */
	462,	/* move_f_to_i4 */
	468,	/* move_i4_to_f */
	0,	/* move_f_to_i8 */
	0,	/* move_i8_to_f */
	0,	/* vzero */
	474,	/* add_imm */
	480,	/* sub_imm */
	486,	/* mul_imm */
	0,	/* div_imm */
	0,	/* div_un_imm */
	0,	/* rem_imm */
	0,	/* rem_un_imm */
	492,	/* and_imm */
	498,	/* or_imm */
	504,	/* xor_imm */
	510,	/* shl_imm */
	516,	/* shr_imm */
	522,	/* shr_un_imm */
	528,	/* br */
	0,	/* jmp */
	534,	/* tailcall */
	540,	/* break */
	546,	/* ceq */
	552,	/* cgt */
	558,	/* cgt.un */
	564,	/* clt */
	570,	/* clt.un */
	576,	/* cond_exc_eq */
	582,	/* cond_exc_ge */
	588,	/* cond_exc_gt */
	594,	/* cond_exc_le */
	600,	/* cond_exc_lt */
	606,	/* cond_exc_ne_un */
	612,	/* cond_exc_ge_un */
	618,	/* cond_exc_gt_un */
	624,	/* cond_exc_le_un */
	630,	/* cond_exc_lt_un */
	636,	/* cond_exc_ov */
	642,	/* cond_exc_no */
	648,	/* cond_exc_c */
	654,	/* cond_exc_nc */
	660,	/* cond_exc_ieq */
	666,	/* cond_exc_ige */
	672,	/* cond_exc_igt */
	678,	/* cond_exc_ile */
	684,	/* cond_exc_ilt */
	690,	/* cond_exc_ine_un */
	696,	/* cond_exc_ige_un */
	702,	/* cond_exc_igt_un */
	708,	/* cond_exc_ile_un */
	714,	/* cond_exc_ilt_un */
	720,	/* cond_exc_iov */
	726,	/* cond_exc_ino */
	732,	/* cond_exc_ic */
	738,	/* cond_exc_inc */
	0,	/* long_add */
	0,	/* long_sub */
	0,	/* long_mul */
	0,	/* long_div */
	0,	/* long_div_un */
	0,	/* long_rem */
	0,	/* long_rem_un */
	0,	/* long_and */
	0,	/* long_or */
	0,	/* long_xor */
	744,	/* long_shl */
	750,	/* long_shr */
	756,	/* long_shr_un */
	0,	/* long_neg */
	0,	/* long_not */
	0,	/* long_conv_to_i1 */
	0,	/* long_conv_to_i2 */
	0,	/* long_conv_to_i4 */
	0,	/* long_conv_to_i8 */
	0,	/* long_conv_to_r4 */
	0,	/* long_conv_to_r8 */
	0,	/* long_conv_to_u4 */
	0,	/* long_conv_to_u8 */
	0,	/* long_conv_to_u2 */
	0,	/* long_conv_to_u1 */
	0,	/* long_conv_to_i */
	0,	/* long_conv_to_ovf_i */
	0,	/* long_conv_to_ovf_u */
	0,	/* long_add_ovf */
	0,	/* long_add_ovf_un */
	0,	/* long_mul_ovf */
	0,	/* long_mul_ovf_un */
	0,	/* long_sub_ovf */
	0,	/* long_sub_ovf_un */
	0,	/* long_conv_to_ovf_i1_un */
	0,	/* long_conv_to_ovf_i2_un */
	0,	/* long_conv_to_ovf_i4_un */
	0,	/* long_conv_to_ovf_i8_un */
	0,	/* long_conv_to_ovf_u1_un */
	0,	/* long_conv_to_ovf_u2_un */
	0,	/* long_conv_to_ovf_u4_un */
	0,	/* long_conv_to_ovf_u8_un */
	0,	/* long_conv_to_ovf_i_un */
	0,	/* long_conv_to_ovf_u_un */
	0,	/* long_conv_to_ovf_i1 */
	0,	/* long_conv_to_ovf_u1 */
	0,	/* long_conv_to_ovf_i2 */
	0,	/* long_conv_to_ovf_u2 */
	0,	/* long_conv_to_ovf_i4 */
	0,	/* long_conv_to_ovf_u4 */
	0,	/* long_conv_to_ovf_i8 */
	0,	/* long_conv_to_ovf_u8 */
	0,	/* long_ceq */
	0,	/* long_cgt */
	0,	/* long_cgt_un */
	0,	/* long_clt */
	0,	/* long_clt_un */
	0,	/* long_conv_to_r_un */
	0,	/* long_conv_to_u */
	0,	/* long_add_imm */
	0,	/* long_sub_imm */
	0,	/* long_mul_imm */
	0,	/* long_and_imm */
	0,	/* long_or_imm */
	0,	/* long_xor_imm */
	762,	/* long_shl_imm */
	768,	/* long_shr_imm */
	774,	/* long_shr_un_imm */
	0,	/* long_div_imm */
	0,	/* long_div_un_imm */
	0,	/* long_rem_imm */
	0,	/* long_rem_un_imm */
	0,	/* long_beq */
	0,	/* long_bge */
	0,	/* long_bgt */
	0,	/* long_ble */
	0,	/* long_blt */
	0,	/* long_bne_un */
	0,	/* long_bge_un */
	0,	/* long_bgt_un */
	0,	/* long_ble_un */
	0,	/* long_blt_un */
	780,	/* long_conv_to_r8_2 */
	786,	/* long_conv_to_r4_2 */
	792,	/* long_conv_to_r_un_2 */
	798,	/* long_conv_to_ovf_i4_2 */
	804,	/* int_add */
	810,	/* int_sub */
	816,	/* int_mul */
	822,	/* int_div */
	828,	/* int_div_un */
	834,	/* int_rem */
	840,	/* int_rem_un */
	846,	/* int_and */
	852,	/* int_or */
	858,	/* int_xor */
	864,	/* int_shl */
	870,	/* int_shr */
	876,	/* int_shr_un */
	882,	/* int_neg */
	888,	/* int_not */
	894,	/* int_conv_to_i1 */
	900,	/* int_conv_to_i2 */
	906,	/* int_conv_to_i4 */
	0,	/* int_conv_to_i8 */
	912,	/* int_conv_to_r4 */
	918,	/* int_conv_to_r8 */
	924,	/* int_conv_to_u4 */
	0,	/* int_conv_to_u8 */
	930,	/* int_conv_to_r_un */
	0,	/* int_conv_to_u */
	936,	/* int_conv_to_u2 */
	942,	/* int_conv_to_u1 */
	948,	/* int_conv_to_i */
	0,	/* int_conv_to_ovf_i */
	0,	/* int_conv_to_ovf_u */
	0,	/* int_add_ovf */
	0,	/* int_add_ovf_un */
	954,	/* int_mul_ovf */
	960,	/* int_mul_ovf_un */
	0,	/* int_sub_ovf */
	0,	/* int_sub_ovf_un */
	0,	/* int_conv_to_ovf_i1_un */
	0,	/* int_conv_to_ovf_i2_un */
	0,	/* int_conv_to_ovf_i4_un */
	0,	/* int_conv_to_ovf_i8_un */
	0,	/* int_conv_to_ovf_u1_un */
	0,	/* int_conv_to_ovf_u2_un */
	0,	/* int_conv_to_ovf_u4_un */
	0,	/* int_conv_to_ovf_u8_un */
	0,	/* int_conv_to_ovf_i_un */
	0,	/* int_conv_to_ovf_u_un */
	0,	/* int_conv_to_ovf_i1 */
	0,	/* int_conv_to_ovf_u1 */
	0,	/* int_conv_to_ovf_i2 */
	0,	/* int_conv_to_ovf_u2 */
	0,	/* int_conv_to_ovf_i4 */
	0,	/* int_conv_to_ovf_u4 */
	0,	/* int_conv_to_ovf_i8 */
	0,	/* int_conv_to_ovf_u8 */
	966,	/* int_adc */
	0,	/* int_adc_imm */
	972,	/* int_sbb */
	0,	/* int_sbb_imm */
	978,	/* int_addcc */
	984,	/* int_subcc */
	990,	/* int_add_imm */
	996,	/* int_sub_imm */
	1002,	/* int_mul_imm */
	1008,	/* int_div_imm */
	1014,	/* int_div_un_imm */
	1020,	/* int_rem_imm */
	1026,	/* int_rem_un_imm */
	1032,	/* int_and_imm */
	1038,	/* int_or_imm */
	1044,	/* int_xor_imm */
	1050,	/* int_shl_imm */
	1056,	/* int_shr_imm */
	1062,	/* int_shr_un_imm */
	1068,	/* int_ceq */
	1074,	/* int_cgt */
	1080,	/* int_cgt_un */
	1086,	/* int_clt */
	1092,	/* int_clt_un */
	1098,	/* int_cneq */
	1104,	/* int_cge */
	1110,	/* int_cle */
	1116,	/* int_cge_un */
	1122,	/* int_cle_un */
	1128,	/* int_beq */
	1134,	/* int_bge */
	1140,	/* int_bgt */
	1146,	/* int_ble */
	1152,	/* int_blt */
	1158,	/* int_bne_un */
	1164,	/* int_bge_un */
	1170,	/* int_bgt_un */
	1176,	/* int_ble_un */
	1182,	/* int_blt_un */
	1188,	/* float_beq */
	1194,	/* float_bge */
	1200,	/* float_bgt */
	1206,	/* float_ble */
	1212,	/* float_blt */
	1218,	/* float_bne_un */
	1224,	/* float_bge_un */
	1230,	/* float_bgt_un */
	1236,	/* float_ble_un */
	1242,	/* float_blt_un */
	0,	/* r4_beq */
	0,	/* r4_bge */
	0,	/* r4_bgt */
	0,	/* r4_ble */
	0,	/* r4_blt */
	0,	/* r4_bne_un */
	0,	/* r4_bge_un */
	0,	/* r4_bgt_un */
	0,	/* r4_ble_un */
	0,	/* r4_blt_un */
	1248,	/* float_add */
	1254,	/* float_sub */
	1260,	/* float_mul */
	1266,	/* float_div */
	1272,	/* float_div_un */
	1278,	/* float_rem */
	1284,	/* float_rem_un */
	0,	/* r4_add */
	0,	/* r4_sub */
	0,	/* r4_mul */
	0,	/* r4_div */
	0,	/* r4_div_un */
	0,	/* r4_rem */
	0,	/* r4_rem_un */
	1290,	/* float_neg */
	1296,	/* float_not */
	1302,	/* float_conv_to_i1 */
	1308,	/* float_conv_to_i2 */
	1314,	/* float_conv_to_i4 */
	1320,	/* float_conv_to_i8 */
	1326,	/* float_conv_to_r4 */
	0,	/* float_conv_to_r8 */
	1332,	/* float_conv_to_u4 */
	1338,	/* float_conv_to_u8 */
	0,	/* r4_neg */
	0,	/* r4_not */
	0,	/* r4_conv_to_i1 */
	0,	/* r4_conv_to_i2 */
	0,	/* r4_conv_to_i4 */
	0,	/* r4_conv_to_i8 */
	0,	/* r4_conv_to_r4 */
	0,	/* r4_conv_to_r8 */
	0,	/* r4_conv_to_u4 */
	0,	/* r4_conv_to_u8 */
	1344,	/* float_conv_to_u2 */
	1350,	/* float_conv_to_u1 */
	1356,	/* float_conv_to_i */
	1362,	/* float_conv_to_ovf_i */
	1368,	/* float_conv_to_ovd_u */
	0,	/* float_add_ovf */
	0,	/* float_add_ovf_un */
	1374,	/* float_mul_ovf */
	0,	/* float_mul_ovf_un */
	0,	/* float_sub_ovf */
	0,	/* float_sub_ovf_un */
	0,	/* float_conv_to_ovf_i1_un */
	0,	/* float_conv_to_ovf_i2_un */
	0,	/* float_conv_to_ovf_i4_un */
	0,	/* float_conv_to_ovf_i8_un */
	0,	/* float_conv_to_ovf_u1_un */
	0,	/* float_conv_to_ovf_u2_un */
	0,	/* float_conv_to_ovf_u4_un */
	0,	/* float_conv_to_ovf_u8_un */
	0,	/* float_conv_to_ovf_i_un */
	0,	/* float_conv_to_ovf_u_un */
	0,	/* float_conv_to_ovf_i1 */
	0,	/* float_conv_to_ovf_u1 */
	0,	/* float_conv_to_ovf_i2 */
	0,	/* float_conv_to_ovf_u2 */
	0,	/* float_conv_to_ovf_i4 */
	0,	/* float_conv_to_ovf_u4 */
	0,	/* float_conv_to_ovf_i8 */
	0,	/* float_conv_to_ovf_u8 */
	1380,	/* float_ceq */
	1386,	/* float_cgt */
	1392,	/* float_cgt_un */
	1398,	/* float_clt */
	1404,	/* float_clt_un */
	1410,	/* float_cneq */
	1416,	/* float_cge */
	1422,	/* float_cle */
	0,	/* float_ceq_membase */
	0,	/* float_cgt_membase */
	0,	/* float_cgt_un_membase */
	0,	/* float_clt_membase */
	0,	/* float_clt_un_membase */
	1428,	/* float_conv_to_u */
	1434,	/* ckfinite */
	0,	/* r4_conv_to_u2 */
	0,	/* r4_conv_to_u1 */
	0,	/* r4_conv_to_i */
	0,	/* r4_conv_to_ovf_i */
	0,	/* r4_conv_to_ovd_u */
	0,	/* r4_add_ovf */
	0,	/* r4_add_ovf_un */
	0,	/* r4_mul_ovf */
	0,	/* r4_mul_ovf_un */
	0,	/* r4_sub_ovf */
	0,	/* r4_sub_ovf_un */
	0,	/* r4_conv_to_ovf_i1_un */
	0,	/* r4_conv_to_ovf_i2_un */
	0,	/* r4_conv_to_ovf_i4_un */
	0,	/* r4_conv_to_ovf_i8_un */
	0,	/* r4_conv_to_ovf_u1_un */
	0,	/* r4_conv_to_ovf_u2_un */
	0,	/* r4_conv_to_ovf_u4_un */
	0,	/* r4_conv_to_ovf_u8_un */
	0,	/* r4_conv_to_ovf_i_un */
	0,	/* r4_conv_to_ovf_u_un */
	0,	/* r4_conv_to_ovf_i1 */
	0,	/* r4_conv_to_ovf_u1 */
	0,	/* r4_conv_to_ovf_i2 */
	0,	/* r4_conv_to_ovf_u2 */
	0,	/* r4_conv_to_ovf_i4 */
	0,	/* r4_conv_to_ovf_u4 */
	0,	/* r4_conv_to_ovf_i8 */
	0,	/* r4_conv_to_ovf_u8 */
	0,	/* r4_ceq */
	0,	/* r4_cgt */
	0,	/* r4_cgt_un */
	0,	/* r4_clt */
	0,	/* r4_clt_un */
	0,	/* r4_cneq */
	0,	/* r4_cge */
	0,	/* r4_cle */
	0,	/* float_getlow32 */
	0,	/* float_gethigh32 */
	1440,	/* jump_table */
	1446,	/* aot_const */
	0,	/* patch_info */
	1452,	/* got_entry */
	1458,	/* call_handler */
	1464,	/* start_handler */
	1470,	/* endfilter */
	1476,	/* endfinally */
	1482,	/* get_ex_obj */
	1488,	/* bigmul */
	1494,	/* bigmul_un */
	1500,	/* int_min_un */
	1506,	/* int_max_un */
	0,	/* long_min_un */
	0,	/* long_max_un */
	0,	/* min */
	0,	/* max */
	1512,	/* int_min */
	1518,	/* int_max */
	0,	/* long_min */
	0,	/* long_max */
	1524,	/* adc */
	1530,	/* adc_imm */
	1536,	/* sbb */
	1542,	/* sbb_imm */
	1548,	/* addcc */
	1554,	/* addcc_imm */
	1560,	/* subcc */
	1566,	/* subcc_imm */
	1572,	/* br_reg */
	1578,	/* sext_i1 */
	1584,	/* sext_i2 */
	0,	/* sext_i4 */
	0,	/* zext_i1 */
	0,	/* zext_i2 */
	0,	/* zext_i4 */
	0,	/* cne */
	0,	/* trunc_i4 */
	0,	/* add_ovf_carry */
	0,	/* sub_ovf_carry */
	0,	/* add_ovf_un_carry */
	0,	/* sub_ovf_un_carry */
	0,	/* laddcc */
	0,	/* lsubcc */
	1590,	/* sin */
	1596,	/* cos */
	1602,	/* abs */
	1608,	/* tan */
	1614,	/* atan */
	1620,	/* sqrt */
	1626,	/* round */
	0,	/* strlen */
	0,	/* newarr */
	0,	/* ldlen */
	0,	/* bounds_check */
	0,	/* isinst */
	0,	/* castclass */
	0,	/* getldelema2 */
	0,	/* memcpy */
	0,	/* memset */
	0,	/* save_lmf */
	0,	/* restore_lmf */
	1632,	/* card_table_wbarrier */
	1638,	/* tls_get */
	0,	/* tls_get_reg */
	1644,	/* tls_set */
	0,	/* tls_set_reg */
	1650,	/* load_gotaddr */
	1656,	/* dummy_use */
	1662,	/* dummy_store */
	1668,	/* not_reached */
	1674,	/* not_null */
	1680,	/* addps */
	1686,	/* divps */
	1692,	/* mulps */
	1698,	/* subps */
	1704,	/* maxps */
	1710,	/* minps */
	1716,	/* compps */
	1722,	/* andps */
	1728,	/* andnps */
	1734,	/* orps */
	1740,	/* xorps */
	1746,	/* haddps */
	1752,	/* hsubps */
	1758,	/* addsubps */
	1764,	/* dupps_low */
	1770,	/* dupps_high */
	1776,	/* rsqrtps */
	1782,	/* sqrtps */
	1788,	/* rcpps */
	1794,	/* pshufflew_high */
	1800,	/* pshufflew_low */
	1806,	/* pshuffled */
	1812,	/* shufps */
	1818,	/* shufpd */
	1824,	/* addpd */
	1830,	/* divpd */
	1836,	/* mulpd */
	1842,	/* subpd */
	1848,	/* maxpd */
	1854,	/* minpd */
	1860,	/* comppd */
	1866,	/* andpd */
	1872,	/* andnpd */
	1878,	/* orpd */
	1884,	/* xorpd */
	1890,	/* haddpd */
	1896,	/* hsubpd */
	1902,	/* addsubpd */
	1908,	/* duppd */
	1914,	/* sqrtpd */
	1920,	/* extract_mask */
	1926,	/* pand */
	1932,	/* por */
	1938,	/* pxor */
	1944,	/* paddb */
	1950,	/* paddw */
	1956,	/* paddd */
	1962,	/* paddq */
	1968,	/* psubb */
	1974,	/* psubw */
	1980,	/* psubd */
	1986,	/* psubq */
	1992,	/* pmaxb_un */
	1998,	/* pmaxw_un */
	2004,	/* pmaxd_un */
	2010,	/* pmaxb */
	2016,	/* pmaxw */
	2022,	/* pmaxd */
	2028,	/* pavgb_un */
	2034,	/* pavgw_un */
	2040,	/* pminb_un */
	2046,	/* pminw_un */
	2052,	/* pmind_un */
	2058,	/* pminb */
	2064,	/* pminw */
	2070,	/* pmind */
	2076,	/* pcmpeqb */
	2082,	/* pcmpeqw */
	2088,	/* pcmpeqd */
	2094,	/* pcmpeqq */
	2100,	/* pcmpgtb */
	2106,	/* pcmpgtw */
	2112,	/* pcmpgtd */
	2118,	/* pcmpgtq */
	2124,	/* psumabsdiff */
	2130,	/* unpack_lowb */
	2136,	/* unpack_loww */
	2142,	/* unpack_lowd */
	2148,	/* unpack_lowq */
	2154,	/* unpack_lowps */
	2160,	/* unpack_lowpd */
	2166,	/* unpack_highb */
	2172,	/* unpack_highw */
	2178,	/* unpack_highd */
	2184,	/* unpack_highq */
	2190,	/* unpack_highps */
	2196,	/* unpack_highpd */
	2202,	/* packw */
	2208,	/* packd */
	2214,	/* packw_un */
	2220,	/* packd_un */
	2226,	/* paddb_sat */
	2232,	/* paddb_sat_un */
	2238,	/* paddw_sat */
	2244,	/* paddw_sat_un */
	2250,	/* psubb_sat */
	2256,	/* psubb_sat_un */
	2262,	/* psubw_sat */
	2268,	/* psubw_sat_un */
	2274,	/* pmulw */
	2280,	/* pmuld */
	2286,	/* pmulq */
	2292,	/* pmul_high_un */
	2298,	/* pmul_high */
	2304,	/* pshrw */
	2310,	/* pshrw_reg */
	2316,	/* psarw */
	2322,	/* psarw_reg */
	2328,	/* pshlw */
	2334,	/* pshlw_reg */
	2340,	/* pshrd */
	2346,	/* pshrd_reg */
	2352,	/* pshrq */
	2358,	/* pshrq_reg */
	2364,	/* psard */
	2370,	/* psard_reg */
	2376,	/* pshld */
	2382,	/* pshld_reg */
	2388,	/* pshlq */
	2394,	/* pshlq_reg */
	2400,	/* extract_i4 */
	0,	/* iconv_to_r4_raw */
	2406,	/* extract_i2 */
	2412,	/* extract_u2 */
	2418,	/* extract_i1 */
	2424,	/* extract_u1 */
	2430,	/* extract_r8 */
	0,	/* extract_i8 */
	0,	/* insert_i1 */
	0,	/* insert_i4 */
	0,	/* insert_i8 */
	0,	/* insert_r4 */
	0,	/* insert_r8 */
	2436,	/* insert_i2 */
	2442,	/* extractx_u2 */
	2448,	/* insertx_u1_slow */
	2454,	/* insertx_i4_slow */
	2460,	/* insertx_r4_slow */
	2466,	/* insertx_r8_slow */
	0,	/* insertx_i8_slow */
	2472,	/* fconv_to_r8_x */
	2478,	/* xconv_r8_to_i4 */
	2484,	/* iconv_to_x */
	0,	/* expand_i1 */
	2490,	/* expand_i2 */
	2496,	/* expand_i4 */
	2502,	/* expand_r4 */
	0,	/* expand_i8 */
	2508,	/* expand_r8 */
	2514,	/* prefetch_membase */
	2520,	/* cvtdq2pd */
	2526,	/* cvtdq2ps */
	2532,	/* cvtpd2dq */
	2538,	/* cvtpd2ps */
	2544,	/* cvtps2dq */
	2550,	/* cvtps2pd */
	2556,	/* cvttpd2dq */
	2562,	/* cvttps2dq */
	0,	/* dpps */
	2568,	/* xmove */
	2574,	/* xzero */
	2580,	/* xones */
	0,	/* xphi */
	2586,	/* memory_barrier */
	2592,	/* atomic_load_i1 */
	2598,	/* atomic_load_i2 */
	2604,	/* atomic_load_i4 */
	0,	/* atomic_load_i8 */
	2610,	/* atomic_load_u1 */
	2616,	/* atomic_load_u2 */
	2622,	/* atomic_load_u4 */
	0,	/* atomic_load_u8 */
	2628,	/* atomic_load_r4 */
	2634,	/* atomic_load_r8 */
	2640,	/* atomic_store_i1 */
	2646,	/* atomic_store_i2 */
	2652,	/* atomic_store_i4 */
	0,	/* atomic_store_i8 */
	2658,	/* atomic_store_u1 */
	2664,	/* atomic_store_u2 */
	2670,	/* atomic_store_u4 */
	0,	/* atomic_store_u8 */
	2676,	/* atomic_store_r4 */
	2682,	/* atomic_store_r8 */
	2688,	/* atomic_add_i4 */
	0,	/* atomic_add_i8 */
	2694,	/* atomic_exchange_i4 */
	0,	/* atomic_exchange_i8 */
	2700,	/* atomic_cas_i4 */
	0,	/* atomic_cas_i8 */
	2706,	/* cmov_ieq */
	2712,	/* cmov_ige */
	2718,	/* cmov_igt */
	2724,	/* cmov_ile */
	2730,	/* cmov_ilt */
	2736,	/* cmov_ine_un */
	2742,	/* cmov_ige_un */
	2748,	/* cmov_igt_un */
	2754,	/* cmov_ile_un */
	2760,	/* cmov_ilt_un */
	0,	/* cmov_leq */
	0,	/* cmov_lge */
	0,	/* cmov_lgt */
	0,	/* cmov_lle */
	0,	/* cmov_llt */
	0,	/* cmov_lne_un */
	0,	/* cmov_lge_un */
	0,	/* cmov_lgt_un */
	0,	/* cmov_lle_un */
	0,	/* cmov_llt_un */
	2766,	/* liverange_start */
	2772,	/* liverange_end */
	2778,	/* gc_liveness_def */
	2784,	/* gc_liveness_use */
	2790,	/* gc_spill_slot_liveness_def */
	2796,	/* gc_param_slot_liveness_def */
	2802,	/* gc_safe_point */
	0,	/* generic_class_init */
	2808,	/* x86_test_null */
	2814,	/* x86_compare_membase_reg */
	2820,	/* x86_compare_membase_imm */
	2826,	/* x86_compare_mem_imm */
	2832,	/* x86_compare_membase8_imm */
	2838,	/* x86_compare_reg_membase */
	2844,	/* x86_inc_reg */
	2850,	/* x86_inc_membase */
	2856,	/* x86_dec_reg */
	2862,	/* x86_dec_membase */
	2868,	/* x86_add_membase_imm */
	2874,	/* x86_sub_membase_imm */
	2880,	/* x86_and_membase_imm */
	2886,	/* x86_or_membase_imm */
	2892,	/* x86_xor_membase_imm */
	2898,	/* x86_add_membase_reg */
	2904,	/* x86_sub_membase_reg */
	2910,	/* x86_and_membase_reg */
	2916,	/* x86_or_membase_reg */
	2922,	/* x86_xor_membase_reg */
	2928,	/* x86_mul_membase_reg */
	2934,	/* x86_add_reg_membase */
	2940,	/* x86_sub_reg_membase */
	2946,	/* x86_mul_reg_membase */
	2952,	/* x86_and_reg_membase */
	2958,	/* x86_or_reg_membase */
	2964,	/* x86_xor_reg_membase */
	2970,	/* x86_push_membase */
	2976,	/* x86_push_imm */
	2982,	/* x86_push */
	2988,	/* x86_push_obj */
	2994,	/* x86_push_got_entry */
	3000,	/* x86_lea */
	3006,	/* x86_lea_membase */
	3012,	/* x86_xchg */
	3018,	/* x86_fpop */
	3024,	/* x86_fp_load_i8 */
	3030,	/* x86_fp_load_i4 */
	3036,	/* x86_seteq_membase */
	3042,	/* x86_setne_membase */
	3048,	/* x86_fxch */
	0,	/* llvm_outarg_vt */
	0,	/* objc_get_selector */
	3054,	/* get_sp */
	3060,	/* set_sp */
	0,	/* get_last_error */
};

